swagger: "3.0"
info:
  title: NITRO SWAGGER API DOCS
  description: NITRO API
  version: 0.0.1
  contact:
    email: calebb.jnr@gmail.com
  license: 
    name: MIT
    url: "http://xyz.com"
  servers:
    -url: "http://localhost:5000",
    description: "DEV SERVER"
    -url: "https://nitro-api.com"
    description: "PROD SERVER"

schemes: [http, https]

paths:
  /fgh:
   get:
     summary: sdfg
     description: fgdfgs