USE NITRO_MOBILE;

CREATE TABLE NITRO_USERS (
    ID BIGSERIAL PRIMARY KEY NOT NULL,
    -- SERIAL FOR AUTO INCREMENT
    CUSTOMER_NAME VARCHAR(255) NOT NULL,
    USERID UUID UNIQUE NULL,
    GENDER VARCHAR(6) NULL,
    EMAIL VARCHAR(125) UNIQUE NULL,
    PASSWORD VARCHAR(125) NOT NULL,
    ACCTNUMBER VARCHAR(10) NULL,
    TPIN VARCHAR(125) NOT NULL,
    STATUS VARCHAR(10) NOT NULL DEFAULT 'ACTIVE',
    PHONENUMBER VARCHAR(15) NULL,
    USERPUSHID VARCHAR(35) NULL,
    TLIMIT VARCHAR(35) NULL,
    DEVICE VARCHAR(24) NOT NULL,
    APPVERSION VARCHAR(8) NULL,
    DATE_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LASTLOGIN TIMESTAMP NULL,
    LOGINCOUNT INT NOT NULL DEFAULT 0
);