CREATE TABLE "USERS" (
    ID BIGSERIAL PRIMARY KEY NOT NULL,
    -- SERIAL FOR AUTO INCREMENT
    CUSTOMER_NAME VARCHAR(255) NOT NULL,
    USERID UUID UNIQUE NULL,
    GENDER VARCHAR(6) NULL,
    EMAIL VARCHAR(125) UNIQUE NULL,
    PASSWORD VARCHAR(125) NOT NULL,
    ACCTNUMBER VARCHAR(10) NULL,
    TPIN VARCHAR(125) NOT NULL,
    STATUS VARCHAR(10) NOT NULL DEFAULT 'ACTIVE',
    PHONENUMBER VARCHAR(15) NULL,
	CARDIDENTIFIER VARCHAR(35) NULL,
    USERPUSHID VARCHAR(35) NULL,
    TLIMIT VARCHAR(35) NOT NULL DEFAULT '1000.00',
    DLIMIT VARCHAR(35) NOT NULL DEFAULT '1000.00',
    D_ULIMIT VARCHAR(35) NOT NULL DEFAULT '0.00',
    DEVICE VARCHAR(24) NOT NULL,
	IP VARCHAR(15) NOT NULL,
    APPVERSION VARCHAR(8) NULL,
    DATE_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LASTLOGIN TIMESTAMP NULL,
	TOKEN VARCHAR(255) NULL,
    LOGINCOUNT INT NOT NULL DEFAULT 0,
    PINCOUNT INT NOT NULL DEFAULT 0
);

CREATE TABLE "TRANSACTIONS" (
    ID BIGSERIAL PRIMARY KEY NOT NULL,
	RequestID UUID UNIQUE NOT NULL,
	USERID UUID NOT NULL, 
	T_TYPE VARCHAR(15) NOT NULL,
	ONETAPMERCHANTID UUID NULL,
	CUSTOMER_NAME VARCHAR(155) NOT NULL,
	CRACCOUNTNO VARCHAR(10) NOT NULL,
	DRACCOUNTNO VARCHAR(10) NOT NULL, 
	AMOUNT DECIMAL(18, 2) NOT NULL,
	CURRENCY VARCHAR(3) NOT NULL,
	NARRACTION VARCHAR(100) NULL,
	BANKCODE VARCHAR(6) NOT NULL,
	REFERENCE_ID VARCHAR(15) NULL,
	SESSION_ID VARCHAR(35) NULL,
	STATUS VARCHAR(50) NOT NULL DEFAULT 'PENDING',
	STATUSCODE VARCHAR(3) NOT NULL DEFAULT '09',
	TDATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	SOURCE VARCHAR(10) NOT NULL,
	TransactionLocation VARCHAR(100) NULL
);

CREATE TABLE "BENEFICIARIES" (
    ID BIGSERIAL PRIMARY KEY NOT NULL,
	USERID UUID NOT NULL,
	CUSTOMER_NAME VARCHAR(155) NOT NULL,
	CRACCOUNTNO VARCHAR(10) UNIQUE NOT NULL,
	BANKCODE VARCHAR(6) NOT NULL
);

-- CREATE TABLE MERCHANTS (
--     ID BIGSERIAL PRIMARY KEY NOT NULL,
-- 	USERID UUID NOT NULL,
--     MERCHANT_NAME VARCHAR(100) NOT NULL,
-- 	EMAIL VARCHAR(125) UNIQUE NULL,
-- 	PHONENUMBER VARCHAR(15) NULL,
--     PASSWORD VARCHAR(125) NOT NULL,
--     MERCHANT_NUBAN VARCHAR(15) NOT NULL,
--     MERCHANT_BANKCODE VARCHAR(6) NOT NULL,
-- 	MERCHANT_STATUS VARCHAR(10) NOT NULL DEFAULT 'ACTIVE',
-- 	MERCHANT_USER_COUNT INT NOT NULL,
-- 	MERCHANT_DEVICEID VARCHAR(100) NOT NULL,
--     DAILYSUCCESSCOUNT BIGINT NOT NULL DEFAULT 0,
--     DAILYFAILCOUNT BIGINT NOT NULL DEFAULT 0,
-- 	LASTTRANSACTIONDATE TIMESTAMP NULL,
-- 	CREATEDATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
-- )